context:
  name: adonisjs
  version: 6.12.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@adonisjs/core/-/core-${{ version }}.tgz
  sha256: ec8ecee54c07194e966b81935abecb042f66432814e8fabf275cc471f4b59bbd

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - adonis-kit --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: AdonisJS is a TypeScript-first web framework for building web apps and API servers.
  homepage: https://github.com/adonisjs/core
  repository: https://github.com/adonisjs/core

extra:
  recipe-maintainers:
    - danielnachun
