context:
  name: adonisjs
  version: "7.3.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@adonisjs/core/-/core-${{ version }}.tgz
  sha256: 378ab33fac7f3fe173ea558dc6d4ab65c0d15dcb7beb6dd6feec409efccf77c4

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - adonis-kit --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: AdonisJS is a TypeScript-first web framework for building web apps and API servers.
  homepage: https://github.com/adonisjs/core
  repository: https://github.com/adonisjs/core

extra:
  recipe-maintainers:
    - danielnachun
