context:
  name: adonisjs
  version: "6.18.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@adonisjs/core/-/core-${{ version }}.tgz
  sha256: 349423480fd86ce2271447d06c8fa0a74b9ecf7b6c4589418fc7ba26cb66823d

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - adonis-kit --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: AdonisJS is a TypeScript-first web framework for building web apps and API servers.
  homepage: https://github.com/adonisjs/core
  repository: https://github.com/adonisjs/core

extra:
  recipe-maintainers:
    - danielnachun
