context:
  name: adonisjs
  version: "7.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@adonisjs/core/-/core-${{ version }}.tgz
  sha256: 7b790e3146b27023f3735cbc021c8f447440d51658cc2040a5a9f81fdfb65e97

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - adonis-kit --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: AdonisJS is a TypeScript-first web framework for building web apps and API servers.
  homepage: https://github.com/adonisjs/core
  repository: https://github.com/adonisjs/core

extra:
  recipe-maintainers:
    - danielnachun
