context:
  name: adonisjs
  version: "7.1.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@adonisjs/core/-/core-${{ version }}.tgz
  sha256: 0fe3a5d00146a9665837e8cb64f7c645f52a8d09fa495411532ba922344ff987

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - adonis-kit --help

about:
  license: MIT
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: AdonisJS is a TypeScript-first web framework for building web apps and API servers.
  homepage: https://github.com/adonisjs/core
  repository: https://github.com/adonisjs/core

extra:
  recipe-maintainers:
    - danielnachun
